[metadata]
creation_date = "2021/02/03"
maturity = "production"
updated_date = "2021/02/03"

[rule]
author = ["Elastic"]
description = """
This rule identifies the attempted use of a Heap-based Buffer Overflow vulnerability for the Sudo binary in Unix-like
systems (CVE-2021-3156). Successful exploitation allows an unprivileged user to escalate to the root user.
"""
false_positives = [
    """
    This rule could generate false positives if the process arguments leveraged by the expoit are shared by custom
    scripts using the Sudo or Sudoedit binaries.
    """,
]
from = "now-9m"
index = ["auditbeat-*", "logs-endpoint.events.*"]
language = "kuery"
license = "Elastic License"
name = "Possible Sudo Heap-based Buffer Overflow Vulnerability (CVE-2021-3156) Attempt"
note = "The rule identifies attempted exploitation of a privilege escalation vulnerability for Sudo. Successful exploitation could allow arbitrary code to be run on the target system with elevated privileges. Alerts from this rule should be invested to identify the validility of the process executions."
references = [
    "https://cve.mitre.org/cgi-bin/cvename.cgi?name=2021-3156",
    "https://blog.qualys.com/vulnerabilities-research/2021/01/26/cve-2021-3156-heap-based-buffer-overflow-in-sudo-baron-samedit",
    "https://www.bleepingcomputer.com/news/security/latest-macos-big-sur-also-has-sudo-root-privilege-escalation-flaw",
]
risk_score = 73
rule_id = "f37f3054-d40b-49ac-aa9b-a786c74c58b8"
severity = "high"
tags = ["Elastic", "Host", "Linux", "macOS", "Threat Detection", "Privilege Escalation"]
type = "query"

query = '''
event.category:process and event.type:start and
  process.name:(sudo or sudoedit) and
  (process.args:*\\ and process.args:("-s" or "-i"))
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1068"
name = "Exploitation for Privilege Escalation"
reference = "https://attack.mitre.org/techniques/T1068/"


[rule.threat.tactic]
id = "TA0004"
name = "Privilege Escalation"
reference = "https://attack.mitre.org/tactics/TA0004/"
[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1059"
name = "Command and Scripting Interpreter"
reference = "https://attack.mitre.org/techniques/T1059/"
[[rule.threat.technique.subtechnique]]
id = "T1059.004"
name = "Unix Shell"
reference = "https://attack.mitre.org/techniques/T1059/004/"



[rule.threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"
[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1078"
name = "Valid Accounts"
reference = "https://attack.mitre.org/techniques/T1078/"
[[rule.threat.technique.subtechnique]]
id = "T1078.003"
name = "Local Accounts"
reference = "https://attack.mitre.org/techniques/T1078/003/"



[rule.threat.tactic]
id = "TA0001"
name = "Initial Access"
reference = "https://attack.mitre.org/tactics/TA0001/"
